# syntax=docker/dockerfile:1

FROM python:3.13.3-slim

WORKDIR /app
COPY server.py /app/
COPY Broker/ /app/Broker/
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN addgroup --system --gid 101 celery && \
    adduser --system --uid 100 --ingroup celery celery



USER celery
EXPOSE 8081

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8081", "--workers" ,"4" ]

