// Code generated by MockGen. DO NOT EDIT.
// Source: search.go
//
// Generated by this command:
//
//	mockgen --source=search.go --destination=./Mocks/mockSearch.go
//

// Package mock_Interfaces is a generated GoMock package.
package mock_Interfaces

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSearch is a mock of Search interface.
type MockSearch struct {
	ctrl     *gomock.Controller
	recorder *MockSearchMockRecorder
}

// MockSearchMockRecorder is the mock recorder for MockSearch.
type MockSearchMockRecorder struct {
	mock *MockSearch
}

// NewMockSearch creates a new mock instance.
func NewMockSearch(ctrl *gomock.Controller) *MockSearch {
	mock := &MockSearch{ctrl: ctrl}
	mock.recorder = &MockSearchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearch) EXPECT() *MockSearchMockRecorder {
	return m.recorder
}

// GetURLFromQuery mocks base method.
func (m *MockSearch) GetURLFromQuery(query string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLFromQuery", query)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLFromQuery indicates an expected call of GetURLFromQuery.
func (mr *MockSearchMockRecorder) GetURLFromQuery(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLFromQuery", reflect.TypeOf((*MockSearch)(nil).GetURLFromQuery), query)
}

// IsURL mocks base method.
func (m *MockSearch) IsURL(input string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsURL", input)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsURL indicates an expected call of IsURL.
func (mr *MockSearchMockRecorder) IsURL(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsURL", reflect.TypeOf((*MockSearch)(nil).IsURL), input)
}
