name: "Test Docker Compose"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-docker-compose:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run docker compose (without tests)
        run: |
          docker-compose --version && \
          docker-compose config > /tmp/docker-compose-config.log

      - name: Check Docker Compose Configuration
        env:
          DOCKER_COMPOSE_CONFIG_LOG_FILE: "/tmp/docker-compose-config.log"
        run: |
          grep "ERROR" "${{env.DOCKER_COMPOSE_CONFIG_LOG_FILE}}" && \
          echo "Docker compose configuration has issues." || true

      - name: Log Docker Compose Configuration
        env:
          DOCKER_COMPOSE_CONFIG_LOG_FILE: "/tmp/docker-compose-config.log"
        run: |
          cat ${DOCKER_COMPOSE_CONFIG_LOG_FILE}
