name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile-path: 
          - { path: ".", tag: "my-image-name-root:$(date +%s)" }
          - { path: "MicroServices/ImageManipulation", tag: "my-image-name-image-manipulation:$(date +%s)" }

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build ${{ matrix.dockerfile-path.path }} --file ${{ matrix.dockerfile-path.path }}/Dockerfile --tag ${{ matrix.dockerfile-path.tag }}
